name: Build APK (BikeLogger)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Jeśli nie ma wrappera gradle — wygeneruje
      - name: Generate Gradle Wrapper (if missing)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          arguments: wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BikeLogger-debug-apk
          path: app/build/outputs/apk/debug/*.apk
